### ISSUE TITLE
You must write ContentLength bytes to the request stream before calling [Begin]GetResponse.

### ISSUE THREAD

**Issue by tmteam** [tmteam/TinyClient#5]
at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state) 
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions) 
at System.Threading.Tasks.TaskFactory.FromAsync[TResult](Func`3 beginMethod, Func`2 endMethod, Object state)
at TinyClient.Client.AsyncRequest.ReceiveAsync()
at TinyClient.Client.AsyncRequest.HandleRequestStream(Task`1 task)
at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
at System.Threading.Tasks.Task.Execute()

"message":"You must write ContentLength bytes to the request stream before calling [Begin]GetResponse.

**Comment by tmteam** [comment]
Not actual
